access key: "eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqaXJhOjZlZWE2NTY5LWI5ZmItNGIyZS1hOGRlLTZlNmQxN2I0ZmZlZSIsImNvbnRleHQiOnsiYmFzZVVybCI6Imh0dHBzOlwvXC9hYi1pbmJldi5hdGxhc3NpYW4ubmV0IiwidXNlciI6eyJhY2NvdW50SWQiOiI1ZGZjZGY5NTlhMTQyNTBjYjY5ZjM1MmQifX0sImlzcyI6ImNvbS5rYW5vYWgudGVzdC1tYW5hZ2VyIiwiZXhwIjoxNjIzODY0NzQxLCJpYXQiOjE1OTIzMjg3NDF9.pa7JvmzGxsZsZwYOaMpNumvOXjTlGUl3n2sffanMrvM"
project key: "BEESPR"
project id: "16104"
java component id: "16135"
test status name: "Automated"
robot report folder: "../../robot-reports"